### ISSUE TITLE
complete dynamics, progress and preservation

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/agda-popl17#11]
write out the dynamics for complete terms and do the proofs that show that we're type safe without holes (should be easy)

**Comment by cyrus-** [comment]
I don't know that this or #12 need to be done for the artifact.

**Comment by ivoysey** [comment]
i had thought of them mostly as due diligence? like they're true and i don't think especially tricky. do you think it's just noise we don't need?

**Comment by cyrus-** [comment]
I mean, you'll need machinery for substitution etc. We don't make any specific claims wrt the dynamics in the paper -- only that you could give complete expressions a standard dynamics. 

Maybe if you can find a clean existing STLC formalism in agda that you can map complete terms into, but I wouldn't bother for POPL.

**Comment by ivoysey** [comment]
i believe substitution is pretty trivial because of barendrecht's convention, at least. but statements of the form "substitution is easy because of X" are exactly the sort of thing one lives to regret.

**Comment by cyrus-** [comment]
yeah... do this last if you want to do it.

**Comment by ivoysey** [comment]
yeah, i agree.

**Comment by ivoysey** [comment]
per discussion, we've decided to not include this in the artifact because it's so standard.
