### ISSUE TITLE
restore determinism of action semantics

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/agda-popl17#16]
this entails fixing #13

**Comment by ivoysey** [comment]
check over the text of determinism to look for redundancies -- places
  where you can underscore on an argument and lose some cases, or something
  similar. anything like that will make it far easier to extend the proof
  for languages with new constructs.

**Comment by ivoysey** [comment]
Can I cut the number of determinism cases in half with command line args to the termination checker?

**Comment by cyrus-** [comment]
Eh?

**Comment by ivoysey** [comment]
size types may be another way to cut the number of cases in half

https://www.reddit.com/r/agda/comments/4ax9xk/sized_types/
