### ISSUE TITLE
make comments and notation consistent with paper

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/agda-popl17#19]
e.g. "focus" -> "cursor" and so on (do a systematic review going through the supplement)

**Comment by ivoysey** [comment]
Also the  left cursor isn't quite the matching arrow to the right, but you can only see it in some fonts.

**Comment by ivoysey** [comment]
what do you mean by going through the supplement? what sorts of inconsistencies have you noticed or are you worried about?

**Comment by cyrus-** [comment]
Not particularly worried about anything, just want to make sure the
terminology is consistent. Would be good to label rules with comments
giving the corresponding rule numbers too, though that can wait until we
have final rule numbers (I did this in the implementation.)

**Comment by ivoysey** [comment]
alright. we can deal with that later as a spit-polish thing, so once i figure out this arrow thing i'll close the issue.

also, alternatively, we could label the rules in the appendix with the constructor names, ideally programmatically.

**Comment by ivoysey** [comment]
the asymmetric rendering of the arrows (as in screenshot) seems to be an artifact of my laptop.
![screen shot 2016-07-20 at 19 09 30](https://cloud.githubusercontent.com/assets/4099104/17006313/fa9f7e62-4ead-11e6-8b2e-07a68b61b4f4.png)
 so i'm going worry about this later, or maybe never.
