### ISSUE TITLE
add comments for fancy unicode

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/agda-popl17#20]
when you define a datatype that uses some fancy rare unicode character, it'd be useful for there to be a comment saying how to enter it using the standard emacs agda thing

**Comment by ivoysey** [comment]
This is exactly `keys.md`. It's slightly but not very much out of date
because I prioritized other things during the run up to the deadline.

---Ian

**Comment by cyrus-** [comment]
Ah OK, didn't notice that. Maybe highlight it in the README too.
