### ISSUE TITLE
erasure

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/agda-popl17#3]
right now there's a weird mix of where i use judgemental versus functional erasure. it induces a bunch of transports everywhere, mostly in the reachability and determinism proofs, and it's messy.

restructure this so that the rules and everything uses the judgement form, except for the outermost theorems that use the metafunction as written in the paper. so keep the iso, but make the whole implementation under the hood use the judgemental form.

**Comment by cyrus-** [comment]
This is done I think?

**Comment by ivoysey** [comment]
yeah, i agree.

it's a little interesting. there are sort of two times that you care about erasure:
- sometimes you want to know what type the erasure of something has, and you want to be able to pattern match on that derivation. this is the case in the main parts of reachability and determinism and sensibility, and that's why those proofs got much smaller and easier to read when i introduced judgmental erasure
- other times, you need to know the specific erasure and how it changes over time. if you do these instances with the judgemental form you need to prove a bunch of silly lemmas like `∀ {e e'} → erase-e e e' → erase-e <| e |> <| e' |>` (https://github.com/hazelgrove/agda-popl17/blob/master/judgemental-erase.agda#L148) which follow immediately from the metafunction definition of erasure because Agda will do some beta reductions under the hood for you to conclude these automatically. this especially happens in some of the zipper lemmas with movements, like https://github.com/hazelgrove/agda-popl17/blob/master/checks.agda#L244

so there's a real balance between when you want to use one or the other. currently i'm using either one as it's convenient, and using the witnesses to the isomorphism to move between them when i have to. i'm happy with that, but i'd love a proof system that did that book keeping for me and really let me treat isomorphic things as equal once i'd proven them iso. this is, i guess, the point of HoTT.
