### ISSUE TITLE
deletability

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/agda-popl17#7]
figure out the theorems that demonstrate that the deletion rules are right and prove them. (some thoughts on this already)

**Comment by cyrus-** [comment]
We decided not to bother with this right?

**Comment by ivoysey** [comment]
did we? i thought we were still trying to figure out exactly what to say.

**Comment by cyrus-** [comment]
I mean we would give a judgemental definition of the deletion of a z-expression separately then print that deletion does that. Seems not worth it.

**Comment by cyrus-** [comment]
prove*

**Comment by ivoysey** [comment]
i guess the question is: if we do that, what class of possible rule errors would it serve to check?

**Comment by cyrus-** [comment]
I think just the ones where the zipper cases special case the delete action, which is not something you'd accidentally do.

**Comment by ivoysey** [comment]
ok. let's not worry about it, then, but remember to include some sort of discussion in the paper about this issue. it's interesting to point out why which kinds rules have checksums (movements, constructs) and which don't (deletes).

what about finishes? i guess since it's also defined without respect to the form of the expression, a "finishability" theorem would only serve to check that you didn't special case the finish rules in your zippers as well?

**Comment by cyrus-** [comment]
Yeah I believe so. Though finishability might also check the definition of the "finish normalizer"?

**Comment by ivoysey** [comment]
yeah, i'll update that so we don't forget about it there and add an issue on the paper repo.
