### ISSUE TITLE
constructability

### ISSUE THREAD

**Issue by ivoysey** [hazelgrove/agda-popl17#9]
- [x] refactor proof to the form that doesn't use the needless judgements, so you can stick whatever you want in the lists whenever you want to
- [ ] define a `finish normal form` and see if that lets you avoid needing to construct filled holes? but that would break the subsume hack, since we specifically envelop the term to protect it from analysis.

**Comment by cyrus-** [comment]
The finish normal firm business should probably be it's own issue?

**Comment by ivoysey** [comment]
yeah, that's a good call.
